### ISSUE TITLE
General lab policies - add off boarding section

### ISSUE THREAD

**Issue by Rios-Jaime** [poldracklab/poldracklab.github.io#40] opened 2024-04-19 18:12 UTC
We should add an off boarding section detailing off boarding policies for folks leaving the lab. For example:

- updating the lab members lab
- making sure their analyses/data have the appropriate permissions on sherlock or are transferred to russ so he has sole control
- return room keys to harry
- etc

**Comment by effigies** [comment] 2024-04-19 18:14
Duplicate of #29. Add your suggestions there?

**Closed by effigies** 2024-04-19 18:14 UTC
